name: Automatizar Blog SEO Cada 3 Dias

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  construir-blog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Actualizar y reorganizar keywords (Detectar borrados)
        run: python actualizar_keywords.py

      - name: Ejecutar script generador de blog
        run: python generar_blog.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Subir artículos y JSON actualizados automáticamente
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-actualización de keywords y generación de nuevo artículo de blog"
